# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa55d37ee0662189c971bb94e09bf182a4bf6bfb2583634c85f0c5a6d241932650bfb94f8334df2a22aa8d35c5c2ffb70430bcc191a1161b74f7f69f866e8db7

test:
  secret_key_base: 28cc1ad15befb4815020a9e2b696c694c986469eb8327f45fb78b1cd2555132ab31c16052c6801939d08253b3345a27877713e4aa52468eb9250621436e9b8fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
