# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0acce2087746fc66ceebf3b06e927e56e8fccfbcb62cb70db7d739a9004b86f72db686fda8e3e87e1a2dcc66685bb645327cd5af2fac5dbbb8c246fe45b6209

test:
  secret_key_base: c3468eb5e3967bc7f1d10dc088dcee3fc595cc8dffb3a9eaf1b0860bd63f374e413eb25e7bcb1e9615b6b5b7a0f3bb6ea038e6787c2e4f4109b73cbf91c03bb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
